# This file is used to define custom add-ons for Home Assistant.
# It specifies the repository, target, image, and version for each add-on.
---
channel: stable
addons:
  heimdall:
    repository: sonic1772/home-assistant-addons/heimdall
    target: heimdall
    image: ghcr.io/benoitanastay/heimdall/{arch}
  paperless_ai:
    repository: sonic1772/home-assistant-addons/paperless_ai
    target: paperless_ai
    image: ghcr.io/clusterzx/paperless-ai/{arch}
