---
name: Paperless AI
version: 0.1.4
slug: paperless_ai
url: https://github.com/clusterzx/paperless-ai
#init: false
description: Chat-basierte KI für Paperless-ngx
webui: http://[HOST]:[PORT:3000]
stage: experimental
arch:
  - amd64
  - aarch64
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Web interface
map:
  - share:rw
  - addon_config:rw
options:
  paperless_ai_port: 3000
schema:
  paperless_ai_port: int

