---
name: Paperless AI
version: 0.1.5.2
slug: paperless_ai
url: https://github.com/clusterzx/paperless-ai
#init: false
description: Chat-basierte KI für Paperless-ngx
webui: http://[HOST]:[PORT:3000]
stage: experimental
arch:
  - amd64
  - aarch64
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Web interface
map:
  - type: addon_config
    read_only: false
options:
  paperless_ai_port: 3000
schema:
  paperless_ai_port: int

